name: Deploy Frontend

on:
    push:
        branches:
            - main # or your frontend branch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd /home/booruledie/Frontend
                      git pull origin main
                      npm ci
                      npm run build
